import game as g

# RENDERING OF UI IN MAIN MENU
# MOVEMENTS ARE NOT SMOOTH (INPUT?)
# ALL TEXTURES, FROM A STRING CODE?
# MAS MODULAR (MÁS METODOS...)
# MAS MOVIMIENTO EN LOS HITS DE LOS BLOQUES
# "TIMESTEPS" EN GAME.
# EVENT_BUS... ¿EN EL LEVEL_MAP?
# INNECESARIA CUSTOMIZACIÓN PARA SUPER MARIO BROS??
# EVENTS QUE AGREGAR AL NIVEL 1.
# SCORE SPAWNING, DEPENDE DEL OBJETO O DE MARIO???
# CAMBIAR TODOS LOS STREAKS DE MARIO.f
# TODOS LOS ENEMIGOS SE VAN A LA IZQUIERDA Y DESAPARECEN CUANDO SE VAN FUERA DEL VIEWPORT. PUNTO.
# NIVEL SECRETO.

# FLAG SCORES. (100 - 5000), depende si terminó en 1, 3 o 6 (FIREWORKS CADA 500 pts)
# MUERTE DE MARIO POR CAIDA.

# REGLA DEL COPY-PASTE. SI ESTOY HACIENDO COPY-PASTE, ALGO HE DE ESTAR HACIENDO MAL. (ESTE CASO XD)
# MARIO GG DE CAER, Y QUE SE REINICIE TODO.s
# CORRECTLY START SONGS.
# HECHO POR ORLANDO

def launch():
    game = g.Game()
    game.start()

if __name__ == "__main__":
    launch()